#!/usr/bin/env python3
"""Regenerate DECISION_LOG.md and decision-tree.md from the ADR records in
docs/decisions/. Run: uv run python scripts/build_decision_log.py

This is a build step. Never hand-edit the two generated files; edit the records
and re-run this script.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml  # from the pyyaml package; parses the YAML frontmatter in each record

# --- Paths -----------------------------------------------------------------
# This file lives in <repo>/scripts/, so parents[1] is the repo root. Resolving
# from __file__ means the script works no matter where it is invoked from.
ROOT = Path(__file__).resolve().parents[1]
DECISIONS_DIR = ROOT / "docs" / "decisions"   # the source of truth: one .md per decision
LOG_OUT = ROOT / "docs" / "DECISION_LOG.md"    # generated table output
TREE_OUT = ROOT / "docs" / "decision-tree.md"  # generated Mermaid diagram output

# Frontmatter fields that are conceptually lists. We normalize each of these to
# an actual list (see parse_record) so later code can iterate without checking
# whether the author wrote `[]`, a single value, or omitted the field.
LIST_FIELDS = ("supersedes", "superseded_by", "relates_to", "tags")


def parse_record(path: Path) -> dict:
    """Read one ADR file, split its YAML frontmatter from its body, and return a
    dict of the metadata plus the body text and filename."""
    text = path.read_text(encoding="utf-8")
    # Every record must open with a `---` frontmatter fence. Fail loudly if not,
    # rather than silently producing a half-broken log.
    if not text.startswith("---"):
        raise ValueError(f"{path.name}: missing YAML frontmatter")
    # The file is: ---\n<frontmatter>\n---\n<body>. Splitting on "---" twice gives
    # ["", frontmatter, body]. maxsplit=2 protects any "---" inside the body.
    _, frontmatter, body = text.split("---", 2)
    meta = yaml.load(frontmatter, Loader=yaml.BaseLoader) or {}  # {} guards against an empty block
    meta["_body"] = body.strip()              # underscore keys = our internal extras
    meta["_file"] = path.name
    # Take the id from the filename's 4-digit prefix, NOT the frontmatter `id:`.
    # YAML reads a leading-zero number as octal, so `id: 0010` parses to 8 and
    # silently collides with 0008. The filename is always the clean 4-digit id,
    # so it is the safe source of truth.
    meta["id"] = path.name[:4]
    # Normalize the list-y fields: None -> [], a bare scalar -> [scalar], list stays.
    for key in LIST_FIELDS:
        val = meta.get(key)
        if not val:
            meta[key] = []
        elif isinstance(val, list):
            meta[key] = val
        else:
            meta[key] = [val]
    return meta


def load_records() -> list[dict]:
    """Find every record file matching the NNNN-*.md naming pattern, parse them,
    and return them sorted by id."""
    # The glob [0-9][0-9][0-9][0-9]-*.md matches a 4-digit id prefix, so helper
    # files like TEMPLATE.md are ignored. sorted() gives a stable filename order.
    records = [parse_record(p) for p in sorted(DECISIONS_DIR.glob("[0-9][0-9][0-9][0-9]-*.md"))]
    # Sort by NUMERIC id. We avoid str() here on purpose: YAML reads a
    # zero-padded id like 0008 as a string but 0001 as the integer 1 (leading
    # zeros mean octal, and 8/9 are not valid octal), so a string sort would put
    # 0008/0009 before 1..7. int() normalizes both forms to a real number.
    records.sort(key=lambda r: int(r.get("id", 0)))
    return records


def fmt_id(value) -> str:
    """Render an id as a zero-padded 4-digit string (e.g. 3 -> '0003') so links
    and node names line up with the file names."""
    return str(value).zfill(4)


def build_log(records: list[dict]) -> str:
    """Build DECISION_LOG.md: a markdown table, one row per record, each id
    linking to its source file."""
    lines = [
        "# Decision Log",
        "",
        "_Generated by `scripts/build_decision_log.py`. Do not edit by hand._",
        "",
        "| ID | Date | Status | Title |",
        "|----|------|--------|-------|",
    ]
    for r in records:
        rid = fmt_id(r.get("id"))
        # The id cell is a relative link into decisions/<file> so the table is
        # clickable when rendered on GitHub.
        lines.append(
            f"| [{rid}](decisions/{r['_file']}) | {r.get('date', '')} "
            f"| {r.get('status', '')} | {r.get('title', '')} |"
        )
    return "\n".join(lines) + "\n"


def build_tree(records: list[dict]) -> str:
    """Build decision-tree.md: a Mermaid `graph TD` where each record is a node,
    supersede links are dotted arrows, and relates_to links are plain edges.
    Node fill color encodes status via the classDef definitions at the bottom."""
    lines = [
        "# Decision Tree",
        "",
        "_Generated by `scripts/build_decision_log.py`. Do not edit by hand._",
        "",
        "```mermaid",
        "graph TD",
    ]
    # First pass: declare a node per record. The :::status suffix attaches a CSS
    # class (defined below) so the node is colored by its lifecycle state.
    for r in records:
        rid = fmt_id(r.get("id"))
        title = str(r.get("title", "")).replace('"', "'")  # quotes would break the label
        lines.append(f'  n{rid}["{rid}: {title}"]:::{r.get("status", "proposed")}')
    # Second pass: draw the edges now that all nodes exist.
    for r in records:
        rid = fmt_id(r.get("id"))
        # "0005 supersedes 0004" is drawn as the older node pointing forward to
        # the newer one with a dotted "superseded by" arrow.
        for sup in r.get("supersedes", []):
            lines.append(f"  n{fmt_id(sup)} -. superseded by .-> n{rid}")
        # relates_to is a non-superseding association: a plain undirected link.
        for rel in r.get("relates_to", []):
            lines.append(f"  n{rid} --- n{fmt_id(rel)}")
    # Status -> color legend. Mermaid applies these to nodes tagged :::<class>.
    lines += [
        "  classDef proposed fill:#fff7e6,stroke:#d4a017;",
        "  classDef accepted fill:#e6f4ea,stroke:#137333;",
        "  classDef superseded fill:#f1f3f4,stroke:#9aa0a6,color:#5f6368;",
        "  classDef deprecated fill:#fce8e6,stroke:#c5221f,color:#5f6368;",
        "```",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    """Load all records, write both generated files, and report what happened.
    Returns a process exit code (0 = success, 1 = no decisions directory)."""
    if not DECISIONS_DIR.exists():
        print(f"No decisions directory at {DECISIONS_DIR}", file=sys.stderr)
        return 1
    records = load_records()
    LOG_OUT.write_text(build_log(records), encoding="utf-8")
    TREE_OUT.write_text(build_tree(records), encoding="utf-8")
    print(f"Wrote {LOG_OUT.relative_to(ROOT)} and {TREE_OUT.relative_to(ROOT)} from {len(records)} records.")
    return 0


if __name__ == "__main__":
    # SystemExit carries our return code to the shell so CI can check it later.
    raise SystemExit(main())